name: Build and 26 workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t keysmustafa/skypro_mnysan_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push keysmustafa/skypro_mnysan_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  diployes:
    runs_on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir diployes
          cat docker-composes-ci.yaml | envsubst > diployes/docker-composes.yaml
          cat docker_cis_config.py | envsubst > diployes/docker_configs.py
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "diploes/docker-composes.yaml,diployes/docker_configs/py"
          target: "flask_app_ci"
          strip_components: 1



